# Config file version is used internally to detect non backward compatible breaks
# All times are in seconds, distances in blocks
Courier:
  UseFees: false
  Version: 0.9.6
  Route:
    InitialWait: 10
    NextRoute: 60
  Postman:
    QuickDespawn: 3
    Despawn: 20
    SpawnDistance: 10
    BreakSpawnProtection: true
    Greeting: 'Courier: A Postman has arrived with your mail!'
    MailDrop: 'Courier: Your mail was dropped onto the ground.'
    Inventory: 'Courier: You had your hands full, the Postman put the mail in your inventory for you.'
    CannotDeliver: 'Courier: A Postman has mail for you but was not allowed in this place.'
  Fee:
    Send: 10