# Config file version is used internally to detect non backward compatible breaks
# All times are in seconds, distances in blocks
# Strings can use &0..&f color coding
# Courier has been tested with Postman.Type 'Enderman' and 'Villager', but will accept all Creature-types
# Route.WalkToPlayer is not used for Monster-Postmen (they would attack), only "friendly mobs".
#   - Set to false if Villager-Postmen keep pushing you into lava ;)
Courier:
  Version: 1.1.8
  UpdateInterval: 18000         # Checks for new versions every 5h. A value of 0 disables.
  UseFees: false
  Fee:
    Send: 10
    BankAccount: <none>
    InfoFee: "&7Courier: &fThe postage is %s"
    InfoNoFee: "&7Courier: &fThere's no cost for sending mail on this server"
  Route:
    InitialWait: 10
    NextRoute: 60
    WalkToPlayer: true
  Privacy:
    SealedEnvelope: true
    Locked: "&0Sorry, only&2 %s\n&0can read this letter"
  Postman:
    Type: 'Enderman'
    QuickDespawn: 3
    Despawn: 20
    SpawnDistance: 10
    BreakSpawnProtection: true
    CreativeDelivery: true
    Greeting: "&7Courier: &fA Postman has arrived with your mail!"
    MailDrop: "&7Courier: &fYour mail was dropped onto the ground."
    Inventory: "&7Courier: &fYou had your hands full, the Postman put the mail in your inventory for you."
    CannotDeliver: "&7Courier: &fA Postman has mail for you but was not allowed in this place."
    ExtraDeliveries: "&7Courier: &fThe Postman will make extra deliveries"
    NoUnreadMail: "&7Courier: &fYou have no unread mail"
  Letter:
    # FreeLetter set to true disables Resources
    FreeLetter: true
    # Multiple amount resources example: [CobbleStone, Paper, CobbleStone]
    Resources: [Coal, Paper]
    # Whether Courier should just deduct the resources or if players need to manually craft letters
    RequiresCrafting: false
    ShowDate: true
    Frameable: true
    Drop: "&7Courier: &fYour inventory is full, the letter was dropped onto the ground."
    Inventory: "&7Courier: &fYou had your hands full, the letter can be found in your inventory."
    NoText: "&7Courier: &fError, no text to add to letter!"
    SkippedText: "&7Courier: &fParts of the entered text cannot be displayed and was skipped"
    CreateFailed: "&7Courier: &fCould not create the letter! Notify your admin!"
    NoMoreUIDs: "&7Courier: &fOut of unique message IDs! Notify your admin!"
    InfoCost: "&7Courier: &fResources needed to create letters: %s."
    InfoFree: "&7Courier: &fLetters don't require any resources to make."
    LackingResources: "&7Courier: &fYou don't have the required resources to create a letter. See /courier fees"
    NoCraftedFound: "&7Courier: &fTo write a letter you first need to craft blank parchment. See /courier fees"
    DisplayName: "Courier Letter"
    From: "&0Letter from&2 %s"
    To: "Letter to %s"
  Parchment:
    DisplayName: "Blank Courier Parchment"
  Post:
    NoCredit: "&7Courier: &fSorry, you don't have enough credit to cover postage (%s)"
    NoRecipient: "&7Courier: &fError, no recipient to post your letter to!"
    DidYouMean: "&7Courier: &fCouldn't find %1$s. Did you mean %2$s?"           # 1$ = input, 2$ = match
    DidYouMeanList: "&7Courier: &fCouldn't find %s. Did you mean anyone of these players?"
    DidYouMeanList2: "&7Courier:&f %s"
    NoSuchPlayer: "&7Courier: &fThere's no player on this server with the name %s"
    LetterSent: "&7Courier: &fLetter to %s sent!"
    LetterSentFee: "&7Courier: &fLetter to %1$s sent! Postage fee of %2$s paid"    # 1$ = recipient, 2$ = fee
    FundProblem: "&7Courier: &fThere was a problem withdrawing funds for postage. Please tell your admin."
    NoLetter: "&7Courier: &fYou must be holding the letter you want to post! See /courier"
  Info:
    Line1: "&f/letter message: &7Creates a letter or adds text to an existing one"
    Line2: "&f/post playername: &7Posts the letter you're holding to playername"
    Line3: "&f/courier fees: &7Lists cost, if any, for creating and posting letters"
    Line4: "&f/courier unread: &7Request re-delivery of any unread mail"